# SPDX-License-Identifier: GPL-2.0
# MediaTek vendor Bluetooth driver for the MT7668 SDIO combo chip,
# ported from the MediaTek reference driver (replaces mainline
# btmtksdio for this chip on the mt7668bt branch).

bt_mt7668-y := btmtk_sdio.o btmtk_main.o

obj-$(CONFIG_BT_MTK7668) += bt_mt7668.o
